version: '{build}'
  
clone_folder: 'c:\development\ctest'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 10 2010"'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 10 2010 Win64"'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 11 2012"'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 11 2012 Win64"'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 12 2013"'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 12 2013 Win64"'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 14 2015" -A Win32'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cmake_generator: '"Visual Studio 14 2015" -A x64'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      cmake_generator: '"Visual Studio 15 2017" -A Win32'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      cmake_generator: '"Visual Studio 15 2017" -A x64'
    
before_build:
  - 'mkdir c:\development\ctest\build'
  - 'cd c:\development\ctest\build'
  - 'cmake .. -G %cmake_generator% -DBUILD_TESTS=1'
    
configuration:
  - Release
  
build:
  project: 'c:\development\ctest\build\ctest.sln'
  
test_script: 
  - 'cd C:\development\ctest\build'
  - 'ctest -C Release'
